name: Analisis de seguridad

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install bandit

      - name: Ejecutar analisis de seguridad
        run: |
          bandit -r .